# Generated by Django 6.0.3 on 2026-04-07 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_date', models.DateField(db_index=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(blank=True, upload_to='dispatch/uploads/%Y/%m/')),
                ('camp_scope', models.CharField(blank=True, max_length=50)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_message', models.TextField(blank=True)),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('ui_state', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_assignment_runs', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='dispatch.dispatchupload')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_code', models.CharField(db_index=True, max_length=100)),
                ('route_prefix', models.CharField(blank=True, max_length=20)),
                ('truck_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('camp_code', models.CharField(blank=True, max_length=50)),
                ('camp_name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_min', models.IntegerField(blank=True, null=True)),
                ('end_min', models.IntegerField(blank=True, null=True)),
                ('stop_count', models.PositiveIntegerField(default=0)),
                ('small_qty', models.PositiveIntegerField(default=0)),
                ('medium_qty', models.PositiveIntegerField(default=0)),
                ('large_qty', models.PositiveIntegerField(default=0)),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('work_minutes', models.PositiveIntegerField(default=0)),
                ('route_meta', models.JSONField(blank=True, default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='dispatch.dispatchupload')),
            ],
            options={
                'ordering': ['route_prefix', 'route_code', 'truck_request_id'],
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_source', models.CharField(choices=[('manual', 'Manual'), ('recommended', 'Recommended'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('assignment_meta', models.JSONField(blank=True, default=dict)),
                ('assignment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='dispatch.assignmentrun')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_assignments', to='dispatch.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='dispatch.route')),
            ],
            options={
                'ordering': ['route__route_prefix', 'route__route_code', 'route__truck_request_id'],
            },
        ),
        migrations.CreateModel(
            name='RouteGroupSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=100)),
                ('group_order', models.PositiveIntegerField(default=1)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('assignment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_suggestions', to='dispatch.assignmentrun')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_suggestions', to='dispatch.route')),
            ],
            options={
                'ordering': ['group_order', 'group_name', 'route__route_prefix', 'route__route_code'],
            },
        ),
        migrations.CreateModel(
            name='ShareSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('snapshot_kind', models.CharField(choices=[('share', 'Share'), ('autosave', 'Autosave'), ('recent', 'Recent')], default='share', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_snapshots', to='dispatch.assignmentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_order', models.PositiveIntegerField()),
                ('house_order', models.PositiveIntegerField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('address_norm', models.CharField(db_index=True, max_length=500)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time_str', models.CharField(blank=True, max_length=20)),
                ('time_minutes', models.IntegerField(blank=True, null=True)),
                ('small_qty', models.PositiveIntegerField(default=0)),
                ('medium_qty', models.PositiveIntegerField(default=0)),
                ('large_qty', models.PositiveIntegerField(default=0)),
                ('is_center', models.BooleanField(default=False)),
                ('center_type', models.CharField(blank=True, max_length=50)),
                ('spu_center', models.CharField(blank=True, max_length=50)),
                ('stop_meta', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.route')),
            ],
            options={
                'ordering': ['route', 'stop_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('upload', 'route_code', 'truck_request_id'), name='dispatch_route_unique_per_upload'),
        ),
        migrations.AddConstraint(
            model_name='routeassignment',
            constraint=models.UniqueConstraint(fields=('assignment_run', 'route'), name='dispatch_route_assignment_unique_per_run_route'),
        ),
        migrations.AddConstraint(
            model_name='routegroupsuggestion',
            constraint=models.UniqueConstraint(fields=('assignment_run', 'route'), name='dispatch_group_suggestion_unique_per_run_route'),
        ),
    ]
