# Generated by Django 6.0.3 on 2026-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('company_id', 'Company ID'), ('address_norm', 'Address Norm')], max_length=20)),
                ('match_key', models.CharField(db_index=True, max_length=500)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('address_norm', models.CharField(blank=True, db_index=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_name', 'match_key'],
                'constraints': [models.UniqueConstraint(fields=('match_type', 'match_key'), name='dispatch_customer_memo_unique_match')],
            },
        ),
    ]
